# Site Settings
locale: "en-US"
title: "Owen Sharp"
title_separator: "-"
subtitle:
name: "Owen Sharp"
description: "Owen Sharp - Projects and CV"
url: "https://cornell-mae-ug.github.io"
baseurl: "/sp26-portfolio-osharp21"

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: light

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /projects/:path/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
